#!/bin/bash

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║        创新凡星系统 - 服务访问信息                        ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "🌐 访问地址:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  📱 前端应用 (用户界面)"
echo "     └─ http://localhost:11000"
echo "        • 登录/注册页面"
echo "        • 聊天界面"
echo "        • 反馈页面"
echo ""
echo "  🔧 后端API (RESTful接口)"
echo "     └─ http://localhost:11013"
echo "        • API基础路径: http://localhost:11013/api"
echo "        • 健康检查: http://localhost:11013/api/health"
echo ""
echo "  💾 数据库 (PostgreSQL)"
echo "     └─ localhost:11002"
echo "        • 用户名: postgres"
echo "        • 密码: postgres"
echo "        • 数据库: chatbot"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 端口映射详情:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  宿主机端口  →  容器端口  →  服务名称"
echo "  ──────────────────────────────────────────────"
echo "  11000      →  80        →  frontend (Nginx)"
echo "  11013      →  3013      →  backend (Node.js)"
echo "  11002      →  5432      →  db (PostgreSQL)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔗 API端点示例:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  用户相关:"
echo "    POST   http://localhost:11013/api/users/register"
echo "    POST   http://localhost:11013/api/users/login"
echo "    GET    http://localhost:11013/api/users/info"
echo ""
echo "  对话相关:"
echo "    GET    http://localhost:11001/api/conversations"
echo "    POST   http://localhost:11001/api/conversations"
echo ""
echo "  消息相关:"
echo "    POST   http://localhost:11001/api/messages"
echo "    GET    http://localhost:11001/api/messages/:conversationId"
echo ""
echo "  管理相关:"
echo "    GET    http://localhost:11001/api/admin/stats"
echo "    GET    http://localhost:11001/api/admin/users"
echo "    PUT    http://localhost:11001/api/admin/users/:id/verify"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 常用命令:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  查看服务状态:  docker-compose ps"
echo "  查看日志:      docker-compose logs -f"
echo "  停止服务:      docker-compose down"
echo "  重启服务:      docker-compose restart"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
